version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fc-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - PORT=4000
    restart: always

  frontend:
    build: ./frontend
    container_name: fc-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
